targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - my.schema.graphql
    builders:
      artemis:
        options:
#          fragments_glob: graphql/fragments/common.graphql
          schema_mapping:
            - schema: my.schema.graphql
              queries_glob: graphql/*.graphql
              output: lib/models/graphql/graphql_api.dart
              naming_scheme: pathedWithFields
          scalar_mapping:
            - graphql_type: UUID
              dart_type: String

            - graphql_type: timestamptz
              dart_type: DateTime

            - graphql_type: timestamp
              dart_type: DateTime

            - graphql_type: uuid
              dart_type: String

            - graphql_type: date
              dart_type: DateTime

            - graphql_type: numeric
              dart_type: double

            - graphql_type: interval
              dart_type: String

            - graphql_type: float8
              dart_type: double

            - graphql_type: geometry
              dart_type: Map

            - graphql_type: geography
              dart_type: Map

            - graphql_type: jsonb
              dart_type: Map

            - graphql_type: bigint
              dart_type: int

            - graphql_type: citext
              dart_type: String

            - graphql_type: Upload
              custom_parser_import: 'package:graphql_toolchain/artemis.dart'
              dart_type:
                name: MultipartFile
                imports:
                  - 'package:http/http.dart'

            - graphql_type: DateTime
              dart_type: DateTime

            - graphql_type: JWT
              dart_type: String
