targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - my.schema.graphql
    builders:
      artemis:
        options:
#          fragments_glob: graphql/fragments/common.graphql
          schema_mapping:
            - schema: my.schema.graphql
              queries_glob: graphql/*.graphql
              output: lib/models/graphql/graphql_api.dart
              naming_scheme: pathedWithFields
              to_json_exclude: true
          scalar_mapping:
            - graphql_type: UUID
              dart_type: String

            - graphql_type: Upload
              custom_parser_import: 'package:graphql_toolchain/artemis.dart'
              dart_type:
                name: MultipartFile
                imports:
                  - 'package:http/http.dart'

            - graphql_type: DateTime
              dart_type: DateTime

            - graphql_type: JWT
              dart_type: String
